name: Update Quote of the Day

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:       # Allows manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests python-dotenv  # Install dependencies including python-dotenv

      - name: Update README with new quote
        run: python daily_quote.py
        env:
          API_NINJA_KEY: ${{ secrets.API_NINJA_KEY }}  # Pass API key from GitHub Secrets

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: 'GitHub Actions'
          author_email: 'actions@github.com'
          message: 'chore: [daily-bot] update quote of the day'
